// --- HSK 2級 データ (指定語句 + 頻出・生活語句で約550語規模を目指して拡充) ---
const hsk2Data = [
  // ■ 指定語句: 名詞 (人物・場所・物)
  { id: 2001, char: "报纸", pinyin: "bàozhǐ", meaning: "新聞", category: "名詞", example: "他手里拿着一张报纸。", exampleMeaning: "彼の手には新聞が握られています。" },
  { id: 2002, char: "宾馆", pinyin: "bīnguǎn", meaning: "ホテル", category: "名詞", example: "她在一家宾馆当服务员。", exampleMeaning: "彼女はホテルで従業員として働いています。" },
  { id: 2003, char: "车站", pinyin: "chēzhàn", meaning: "駅、バス停", category: "名詞", example: "我在车站等你。", exampleMeaning: "駅であなたを待っています。" },
  { id: 2004, char: "房间", pinyin: "fángjiān", meaning: "部屋", category: "名詞", example: "我们两个人住一个房间。", exampleMeaning: "私たち2人は1つの部屋に住んでいます。" },
  { id: 2005, char: "服务员", pinyin: "fúwùyuán", meaning: "従業員、店員", category: "名詞", example: "这个饭店的服务员很热情。", exampleMeaning: "このホテルの従業員はとても親切です。" },
  { id: 2006, char: "哥哥", pinyin: "gēge", meaning: "兄", category: "名詞", example: "这是我哥哥的汽车。", exampleMeaning: "これは私の兄の車です。" },
  { id: 2007, char: "公共汽车", pinyin: "gōnggòng qìchē", meaning: "バス", category: "名詞", example: "我们坐公共汽车去吧。", exampleMeaning: "私たちはバスで行きましょう。" },
  { id: 2008, char: "公司", pinyin: "gōngsī", meaning: "会社", category: "名詞", example: "昨天我没上公司去。", exampleMeaning: "昨日は会社に行きませんでした。" },
  { id: 2009, char: "孩子", pinyin: "háizi", meaning: "子供", category: "名詞", example: "这孩子真聪明。", exampleMeaning: "この子供はとても賢いです。" },
  { id: 2010, char: "火车站", pinyin: "huǒchēzhàn", meaning: "駅", category: "名詞", example: "我们三点在火车站见面。", exampleMeaning: "私たちは3時に駅で会きましょう。" },
  { id: 2011, char: "教室", pinyin: "jiàoshì", meaning: "教室", category: "名詞", example: "我们的教室在哪儿？", exampleMeaning: "私たちの教室はどこですか。" },
  { id: 2012, char: "机场", pinyin: "jīchǎng", meaning: "空港", category: "名詞", example: "我下飞机后在机场等你吧。", exampleMeaning: "私は飛行機から降りた後、空港であなたを待っていますね。" },
  { id: 2013, char: "鸡蛋", pinyin: "jīdàn", meaning: "卵", category: "名詞", example: "我爱吃西红柿炒鸡蛋。", exampleMeaning: "私はトマトと卵の炒め物を食べるのが好きです。" },
  { id: 2014, char: "姐姐", pinyin: "jiějie", meaning: "姉", category: "名詞", example: "这是我姐姐的自行车。", exampleMeaning: "これは私の姉の自転車です。" },
  { id: 2015, char: "咖啡", pinyin: "kāfēi", meaning: "コーヒー", category: "名詞", example: "这种咖啡味道很好。", exampleMeaning: "このコーヒーの味はとても良いです。" },
  { id: 2016, char: "课", pinyin: "kè", meaning: "授業", category: "名詞", example: "我们明天开始学习新课。", exampleMeaning: "私たちは明日から新しい課を学び始めます。" },
  { id: 2017, char: "路", pinyin: "lù", meaning: "道", category: "名詞", example: "这条路不太好走。", exampleMeaning: "この道はあまり通りやすくありません。" },
  { id: 2018, char: "妹妹", pinyin: "mèimei", meaning: "妹", category: "名詞", example: "我妹妹刚上小学。", exampleMeaning: "私の妹はちょうど小学校に上がったばかりです。" },
  { id: 2019, char: "门", pinyin: "mén", meaning: "ドア、門", category: "名詞", example: "这个公园有四个门。", exampleMeaning: "この公園には4つの門があります。" },
  { id: 2020, char: "面条", pinyin: "miàntiáo", meaning: "麺類", category: "名詞", example: "我想吃饺子，可是妈妈做了面条。", exampleMeaning: "私は餃子が食べたかったのですが、母は麺を作りました。" },
  { id: 2021, char: "牛奶", pinyin: "niúnǎi", meaning: "牛乳", category: "名詞", example: "冰箱里的牛奶喝完了。", exampleMeaning: "冷蔵庫の中の牛乳は全部飲み終わった。" },
  { id: 2022, char: "旁边", pinyin: "pángbiān", meaning: "隣、そば", category: "名詞", example: "我旁边这位是李老师。", exampleMeaning: "私の隣のこの方は李先生です。" },
  { id: 2023, char: "票", pinyin: "piào", meaning: "チケット", category: "名詞", example: "我买了两张电影票。", exampleMeaning: "私は映画のチケットを2枚買いました。" },
  { id: 2024, char: "铅笔", pinyin: "qiānbǐ", meaning: "鉛筆", category: "名詞", example: "你能借我一支铅笔吗？", exampleMeaning: "鉛筆を1本貸してくれませんか。" },
  { id: 2025, char: "妻子", pinyin: "qīzi", meaning: "妻", category: "名詞", example: "我和我妻子都是老师。", exampleMeaning: "私と妻はともに教師です。" },
  { id: 2026, char: "去年", pinyin: "qùnián", meaning: "去年", category: "名詞", example: "我去年来过一次北京。", exampleMeaning: "私は去年1度北京に来たことがあります。" },
  { id: 2027, char: "生日", pinyin: "shēngrì", meaning: "誕生日", category: "名詞", example: "明天是我妈妈的生日。", exampleMeaning: "明日は母の誕生日です。" },
  { id: 2028, char: "身体", pinyin: "shēntǐ", meaning: "体、健康", category: "名詞", example: "你最近身体好吗？", exampleMeaning: "最近お元気ですか。" },
  { id: 2029, char: "时间", pinyin: "shíjiān", meaning: "時間", category: "名詞", example: "明天你有时间吗？", exampleMeaning: "明日お時間ございますか。" },
  { id: 2030, char: "事情", pinyin: "shìqing", meaning: "こと、用事", category: "名詞", example: "这件事情很麻烦。", exampleMeaning: "このことはとても煩わしいです。" },
  { id: 2031, char: "手表", pinyin: "shǒubiǎo", meaning: "腕時計", category: "名詞", example: "这块手表我戴了二十年了。", exampleMeaning: "私はこの腕時計を20年使っています。" },
  { id: 2032, char: "手机", pinyin: "shǒujī", meaning: "携帯電話", category: "名詞", example: "你的手机号码是多少？", exampleMeaning: "携帯番号はいくつですか。" },
  { id: 2033, char: "题", pinyin: "tí", meaning: "問題", category: "名詞", example: "我们一起做这个题吧。", exampleMeaning: "私たちは一緒にこの問題を解きましょう。" },
  { id: 2034, char: "外", pinyin: "wài", meaning: "外", category: "名詞", example: "窗外有一棵大树。", exampleMeaning: "窓の外には大きな木があります。" },
  { id: 2035, char: "晚上", pinyin: "wǎnshang", meaning: "夜", category: "名詞", example: "晚上我们一起去看电影吧。", exampleMeaning: "夜、私たちは一緒に映画を見に行きましょう。" },
  { id: 2036, char: "问题", pinyin: "wèntí", meaning: "問題、質問", category: "名詞", example: "大家还有什么问题？", exampleMeaning: "皆さん他に質問はありますか。" },
  { id: 2037, char: "小时", pinyin: "xiǎoshí", meaning: "時間（長さ）", category: "名詞", example: "从北京到上海坐火车要几个小时？", exampleMeaning: "北京から上海まで電車で何時間かかりますか？" },
  { id: 2038, char: "西瓜", pinyin: "xīguā", meaning: "スイカ", category: "名詞", example: "这个西瓜很好吃。", exampleMeaning: "このスイカはとても美味しいです。" },
  { id: 2039, char: "雪", pinyin: "xuě", meaning: "雪", category: "名詞", example: "昨天晚上下雪了。", exampleMeaning: "昨日の夜は雪が降りました。" },
  { id: 2040, char: "羊肉", pinyin: "yángròu", meaning: "羊肉", category: "名詞", example: "这个饭店做的羊肉特别好吃。", exampleMeaning: "このレストランのラム肉はとりわけ美味しい。" },
  { id: 2041, char: "眼睛", pinyin: "yǎnjing", meaning: "目", category: "名詞", example: "要注意保护你的眼睛。", exampleMeaning: "あなたの目を守るように気をつけないといけません。" },
  { id: 2042, char: "颜色", pinyin: "yánsè", meaning: "色", category: "名詞", example: "这件红颜色的衣服很好看。", exampleMeaning: "この赤色の服はとても綺麗です。" },
  { id: 2043, char: "药", pinyin: "yào", meaning: "薬", category: "名詞", example: "你吃过药了吗？", exampleMeaning: "薬を飲みましたか。" },
  { id: 2044, char: "意思", pinyin: "yìsi", meaning: "意味", category: "名詞", example: "这句话是什么意思？", exampleMeaning: "この言葉はどういう意味ですか。" },
  { id: 2045, char: "右边", pinyin: "yòubian", meaning: "右側", category: "名詞", example: "你的右边有人吗？", exampleMeaning: "あなたの右側に人はいますか。" },
  { id: 2046, char: "鱼", pinyin: "yú", meaning: "魚", category: "名詞", example: "这条河里有很多鱼。", exampleMeaning: "この川にはたくさんの魚がいます。" },
  { id: 2047, char: "早上", pinyin: "zǎoshang", meaning: "朝", category: "名詞", example: "我每天早上七点到公司。", exampleMeaning: "私は毎朝7時に会社に着きます。" },
  { id: 2048, char: "丈夫", pinyin: "zhàngfu", meaning: "夫", category: "名詞", example: "你想找个什么样的丈夫？", exampleMeaning: "あなたはどんな夫がいいですか？" },
  { id: 2049, char: "左边", pinyin: "zuǒbian", meaning: "左側", category: "名詞", example: "他坐在了左边的椅子上。", exampleMeaning: "彼は左側の椅子に座りました。" },

  // ■ HSK 2級 指定語句 (動詞)
  { id: 2050, char: "帮助", pinyin: "bāngzhù", meaning: "助ける", category: "動詞", example: "我们是好朋友，应该互相帮助。", exampleMeaning: "私たちは仲の良い友だちなので、お互い助け合うべきです。" },
  { id: 2051, char: "唱歌", pinyin: "chàng gē", meaning: "歌を歌う", category: "動詞", example: "我们一起去唱歌，好吗？", exampleMeaning: "一緒に歌を歌いに行きませんか。" },
  { id: 2052, char: "出", pinyin: "chū", meaning: "出る", category: "動詞", example: "出了大门，就是商店。", exampleMeaning: "正門を出ると、お店があります。" },
  { id: 2053, char: "穿", pinyin: "chuān", meaning: "着る", category: "動詞", example: "她穿着一件红毛衣。", exampleMeaning: "彼女は赤いセーターを着ています。" },
  { id: 2054, char: "到", pinyin: "dào", meaning: "着く", category: "動詞", example: "飞机已经到北京了。", exampleMeaning: "飛行機はすでに北京に到着しました。" },
  { id: 2055, char: "等", pinyin: "děng", meaning: "待つ", category: "動詞", example: "别着急，我们等你。", exampleMeaning: "急がないでください、私たちはあなたを待っています。" },
  { id: 2056, char: "懂", pinyin: "dǒng", meaning: "分かる", category: "動詞", example: "你的意思我懂了。", exampleMeaning: "あなたの言いたいことは分かりました。" },
  { id: 2057, char: "告诉", pinyin: "gàosu", meaning: "伝える", category: "動詞", example: "我想告诉你一件事。", exampleMeaning: "あなたに伝えたいことがあります。" },
  { id: 2058, char: "给", pinyin: "gěi", meaning: "あげる、〜に", category: "動詞", example: "给我一杯水吧。", exampleMeaning: "水を1杯ください。" },
  { id: 2059, char: "介绍", pinyin: "jièshào", meaning: "紹介する", category: "動詞", example: "请你介绍一下自己。", exampleMeaning: "自己紹介をお願いします。" },
  { id: 2060, char: "进", pinyin: "jìn", meaning: "入る", category: "動詞", example: "请大家进屋来坐吧。", exampleMeaning: "どうぞ皆さん中に入って座ってください。" },
  { id: 2061, char: "觉得", pinyin: "juéde", meaning: "思う", category: "動詞", example: "我突然觉得身体不舒服。", exampleMeaning: "私は急に体調が悪くなりました。" },
  { id: 2062, char: "开始", pinyin: "kāishǐ", meaning: "始まる", category: "動詞", example: "比赛什么时候开始？", exampleMeaning: "試合はいつ始まりますか。" },
  { id: 2063, char: "考试", pinyin: "kǎoshì", meaning: "試験を受ける", category: "動詞", example: "我们下个星期考试。", exampleMeaning: "私たちは来週試験を受けます。" },
  { id: 2064, char: "离", pinyin: "lí", meaning: "離れる", category: "動詞", example: "他离家已经两年多了。", exampleMeaning: "彼が家を出てから2年以上経ちます。" },
  { id: 2065, char: "旅游", pinyin: "lǚyóu", meaning: "旅行する", category: "動詞", example: "这次旅游我非常快乐。", exampleMeaning: "今回の旅行、私はとても楽しかったです。" },
  { id: 2066, char: "卖", pinyin: "mài", meaning: "売る", category: "動詞", example: "你这苹果怎么卖？", exampleMeaning: "あなたはこのリンゴをどのように売りますか(いくらですか)。" },
  { id: 2067, char: "跑步", pinyin: "pǎobù", meaning: "ジョギングする", category: "動詞", example: "今天早上我跑了半个小时的步。", exampleMeaning: "今朝、私は30分ジョギングしました。" },
  { id: 2068, char: "起床", pinyin: "qǐchuáng", meaning: "起きる", category: "動詞", example: "你每天什么时候起床？", exampleMeaning: "あなたは毎日いつ起きますか。" },
  { id: 2069, char: "让", pinyin: "ràng", meaning: "譲る、させる", category: "動詞", example: "这个机会他让给别人了。", exampleMeaning: "このチャンスを彼はほかの人に譲りました。" },
  { id: 2070, char: "上班", pinyin: "shàngbān", meaning: "出勤する", category: "動詞", example: "我每天早晨八点上班。", exampleMeaning: "私は毎朝8時に出勤します。" },
  { id: 2071, char: "生病", pinyin: "shēngbìng", meaning: "病気になる", category: "動詞", example: "他经常运动，很少生病。", exampleMeaning: "彼はいつも運動するので、めったに病気をしません。" },
  { id: 2072, char: "说话", pinyin: "shuōhuà", meaning: "話をする", category: "動詞", example: "请大家不要说话了。", exampleMeaning: "皆さんお静かに。" },
  { id: 2073, char: "送", pinyin: "sòng", meaning: "送る、届ける", category: "動詞", example: "我一会儿给你送过去。", exampleMeaning: "しばらくしてからあなたに持っていきます。" },
  { id: 2074, char: "跳舞", pinyin: "tiàowǔ", meaning: "踊る", category: "動詞", example: "她每天早上去公园里跳舞。", exampleMeaning: "彼女は毎朝公園に行って踊ります。" },
  { id: 2075, char: "完", pinyin: "wán", meaning: "終わる", category: "動詞", example: "你的工作什么时候完啊？", exampleMeaning: "あなたの仕事はいつ終わりますか。" },
  { id: 2076, char: "玩", pinyin: "wán", meaning: "遊ぶ", category: "動詞", example: "孩子们在外面玩儿呢。", exampleMeaning: "子供たちは外で遊んでいます。" },
  { id: 2077, char: "问", pinyin: "wèn", meaning: "聞く、尋ねる", category: "動詞", example: "这个问题你问老师吧。", exampleMeaning: "この問題は先生に聞いてみて。" },
  { id: 2078, char: "洗", pinyin: "xǐ", meaning: "洗う", category: "動詞", example: "衣服洗得真干净。", exampleMeaning: "服は本当にきれいに洗ってあります。" },
  { id: 2079, char: "笑", pinyin: "xiào", meaning: "笑う", category: "動詞", example: "他笑起来很好看。", exampleMeaning: "彼は笑うととてもかっこいいです。" },
  { id: 2080, char: "姓", pinyin: "xìng", meaning: "苗字、〜という", category: "動詞", example: "在中国，姓“李”的人最多。", exampleMeaning: "中国では、李という姓の人が最も多い。" },
  { id: 2081, char: "休息", pinyin: "xiūxi", meaning: "休む", category: "動詞", example: "老师，我们休息一下吧。", exampleMeaning: "先生、私たちは少し休みましょう。" },
  { id: 2082, char: "希望", pinyin: "xīwàng", meaning: "望む、〜したい", category: "動詞", example: "真希望今年暑假能去旅游。", exampleMeaning: "今年の夏休みは旅行にとても行きたいです。" },
  { id: 2083, char: "游泳", pinyin: "yóuyǒng", meaning: "泳ぐ", category: "動詞", example: "我弟弟游泳游得非常快。", exampleMeaning: "私の弟は泳ぐのがとても速い。" },
  { id: 2084, char: "运动", pinyin: "yùndòng", meaning: "運動する", category: "動詞", example: "很多人喜欢在早上运动。", exampleMeaning: "多くの人は早朝に運動するのが好きです。" },
  { id: 2085, char: "找", pinyin: "zhǎo", meaning: "探す", category: "動詞", example: "请问，您找谁？", exampleMeaning: "すみません、どなたにご用ですか。" },
  { id: 2086, char: "知道", pinyin: "zhīdao", meaning: "知っている", category: "動詞", example: "我知道他昨天为什么没来。", exampleMeaning: "私は彼が昨日なぜ来なかったかを知っています。" },
  { id: 2087, char: "准备", pinyin: "zhǔnbèi", meaning: "準備する", category: "動詞", example: "他正在准备下周的考试。", exampleMeaning: "彼は今来週のテストの準備をしています。" },
  { id: 2088, char: "走", pinyin: "zǒu", meaning: "歩く、離れる", category: "動詞", example: "我走累了，咱们休息一下吧。", exampleMeaning: "歩き疲れました。私たちは少し休憩しましょう。" },

  // ■ HSK 2級 指定語句 (形容詞・その他)
  { id: 2089, char: "白", pinyin: "bái", meaning: "白い", category: "形容詞", example: "她穿了一件白衬衫。", exampleMeaning: "彼女は白いブラウスを着ています。" },
  { id: 2090, char: "长", pinyin: "cháng", meaning: "長い", category: "形容詞", example: "这件衣服比那件长很多。", exampleMeaning: "この服はあの服よりずっと長いです。" },
  { id: 2091, char: "错", pinyin: "cuò", meaning: "間違う", category: "形容詞", example: "学汉语要敢说，说错了也没关系。", exampleMeaning: "中国語を学ぶには勇気をもって話さなければなりません。間違っても大丈夫です。" },
  { id: 2092, char: "高", pinyin: "gāo", meaning: "高い", category: "形容詞", example: "他比我高很多。", exampleMeaning: "彼は私よりずっと背が高いです。" },
  { id: 2093, char: "贵", pinyin: "guì", meaning: "高い(値段)", category: "形容詞", example: "这里的东西都很贵。", exampleMeaning: "ここの物はすべてとても高いです。" },
  { id: 2094, char: "好吃", pinyin: "hǎochī", meaning: "美味しい", category: "形容詞", example: "你做的菜太好吃了。", exampleMeaning: "あなたの作った料理はとても美味しいです。" },
  { id: 2095, char: "黑", pinyin: "hēi", meaning: "黒い", category: "形容詞", example: "他穿着一件黑衬衫。", exampleMeaning: "彼は黒いワイシャツを着ています。" },
  { id: 2096, char: "红", pinyin: "hóng", meaning: "赤い", category: "形容詞", example: "我爱吃这种红苹果。", exampleMeaning: "私はこの赤いリンゴを食べるのが好きです。" },
  { id: 2097, char: "近", pinyin: "jìn", meaning: "近い", category: "形容詞", example: "我家离学校很近。", exampleMeaning: "我が家は学校からとても近いです。" },
  { id: 2098, char: "快", pinyin: "kuài", meaning: "速い", category: "形容詞", example: "他说话太快了，我没听懂。", exampleMeaning: "彼は話すのがとても速いので、聞き取れません。" },
  { id: 2099, char: "快乐", pinyin: "kuàilè", meaning: "楽しい", category: "形容詞", example: "他们在中国生活得很快乐。", exampleMeaning: "彼らは中国で楽しく生活しています。" },
  { id: 2100, char: "累", pinyin: "lèi", meaning: "疲れる", category: "形容詞", example: "这几天工作太累了。", exampleMeaning: "この何日間、仕事がとても大変です。" },
  { id: 2101, char: "慢", pinyin: "màn", meaning: "遅い、ゆっくり", category: "形容詞", example: "请你说慢一点儿。", exampleMeaning: "もう少しゆっくり話してくれませんか。" },
  { id: 2102, char: "忙", pinyin: "máng", meaning: "忙しい", category: "形容詞", example: "最近我很忙。", exampleMeaning: "最近私はとても忙しいです。" },
  { id: 2103, char: "便宜", pinyin: "piányi", meaning: "安い", category: "形容詞", example: "能不能便宜点儿？", exampleMeaning: "もう少し安くできませんか。" },
  { id: 2104, char: "晴", pinyin: "qíng", meaning: "晴れ", category: "形容詞", example: "今天晴转阴。", exampleMeaning: "今日は晴れのち曇りです。" },
  { id: 2105, char: "新", pinyin: "xīn", meaning: "新しい", category: "形容詞", example: "这是我的新手表，你看怎么样？", exampleMeaning: "これは私の新しい腕時計です。どう思いますか？" },
  { id: 2106, char: "阴", pinyin: "yīn", meaning: "曇り", category: "形容詞", example: "今天阴天，可能会下雨。", exampleMeaning: "今日は曇りですので、恐らく雨が降るでしょう。" },
  { id: 2107, char: "远", pinyin: "yuǎn", meaning: "遠い", category: "形容詞", example: "我家离学校很远。", exampleMeaning: "我が家は学校からとても遠いです。" },
  { id: 2108, char: "别", pinyin: "bié", meaning: "〜するな", category: "副詞", example: "别着急，会由办法的。", exampleMeaning: "焦らないでください、方法はありますので。" },
  { id: 2109, char: "非常", pinyin: "fēicháng", meaning: "とても、非常に", category: "副詞", example: "这个房间非常干净。", exampleMeaning: "この部屋はとてもきれいです。" },
  { id: 2110, char: "还", pinyin: "hái", meaning: "さらに、まだ", category: "副詞", example: "他会唱歌，还会跳舞。", exampleMeaning: "彼は歌が上手で、さらに踊りも上手です。" },
  { id: 2111, char: "就", pinyin: "jiù", meaning: "すぐに", category: "副詞", example: "我马上就来。", exampleMeaning: "すぐに参ります。" },
  { id: 2112, char: "可能", pinyin: "kěnéng", meaning: "恐らく", category: "副詞", example: "天阴了，可能要下雨。", exampleMeaning: "曇りになったので、恐らく雨が降るでしょう。" },
  { id: 2113, char: "哪儿", pinyin: "nǎr", meaning: "どこ", category: "代名詞", example: "他去哪儿了？", exampleMeaning: "彼はどこに行きましたか。" },
  { id: 2114, char: "谁", pinyin: "shéi", meaning: "誰", category: "代名詞", example: "请问，您找谁？", exampleMeaning: "すみません、どなたをお探しですか。" },
  { id: 2115, char: "什么", pinyin: "shénme", meaning: "何", category: "代名詞", example: "你最喜欢什么运动？", exampleMeaning: "あなたは何のスポーツが一番好きですか。" },
  { id: 2116, char: "怎么", pinyin: "zěnme", meaning: "どう、どのように", category: "代名詞", example: "他怎么一句话也不说呀？", exampleMeaning: "彼はどうして一言も話さないのでしょうか？" },
  { id: 2117, char: "怎么样", pinyin: "zěnmeyàng", meaning: "どう、どのような", category: "代名詞", example: "你最近身体怎么样啊？", exampleMeaning: "最近お体の調子はどうですか。" },
  { id: 2118, char: "那", pinyin: "nà", meaning: "あれ、それ", category: "代名詞", example: "那是我哥哥。", exampleMeaning: "あれは私の兄です。" },
  { id: 2119, char: "您", pinyin: "nín", meaning: "あなた（敬称）", category: "代名詞", example: "您今年多大年纪？", exampleMeaning: "あなたは今年おいくつになられましたか。" },
  { id: 2120, char: "它", pinyin: "tā", meaning: "それ（動物・物）", category: "代名詞", example: "我家有只小狗，它很可爱。", exampleMeaning: "我が家には子犬がいて、それはとても可愛いです。" },
  { id: 2121, char: "大家", pinyin: "dàjiā", meaning: "みなさん", category: "代名詞", example: "见到你，大家都很高兴。", exampleMeaning: "あなたに会うと、みんなとても喜びます。" },
  { id: 2122, char: "每", pinyin: "měi", meaning: "それぞれの", category: "代名詞", example: "每个人都有自己的爱好。", exampleMeaning: "人はそれぞれが自分の趣味を持っている。" },
  { id: 2123, char: "为什么", pinyin: "wèishénme", meaning: "なぜ", category: "代名詞", example: "你为什么学习汉语？", exampleMeaning: "あなたはなぜ中国語を勉強するのですか。" },
  { id: 2124, char: "零", pinyin: "líng", meaning: "0", category: "数詞", example: "我住三零五房间。", exampleMeaning: "私は305号室に住んでいます。" },
  { id: 2125, char: "百", pinyin: "bǎi", meaning: "100", category: "数詞", example: "这本书一百块钱。", exampleMeaning: "この本は100元です。" },
  { id: 2126, char: "千", pinyin: "qiān", meaning: "1000", category: "数詞", example: "我认识两千多个汉字了。", exampleMeaning: "私は2000字の漢字を知っています。" },
  { id: 2127, char: "第一", pinyin: "dì yī", meaning: "一番", category: "数詞", example: "他每次游泳比赛都是第一。", exampleMeaning: "彼は毎回水泳大会で一番です。" },
  { id: 2128, char: "两", pinyin: "liǎng", meaning: "2", category: "数詞", example: "我买了两本书。", exampleMeaning: "私は本を2冊買いました。" },
  { id: 2129, char: "次", pinyin: "cì", meaning: "回", category: "量詞", example: "我去过两次美国。", exampleMeaning: "私はアメリカに2度行ったことがあります。" },

  // ■ HSK 2級 頻出語句 (抜粋)
  { id: 2130, char: "爸", pinyin: "bà", meaning: "お父さん", category: "名詞", example: "这是我爸的汽车。", exampleMeaning: "これは私の父の自動車です。" },
  { id: 2131, char: "部分", pinyin: "bùfen", meaning: "部分", category: "名詞", example: "我还有一部分工作没做完。", exampleMeaning: "私はまだ仕事の一部が終わっていません。" },
  { id: 2132, char: "车", pinyin: "chē", meaning: "車", category: "名詞", example: "我的车停在那儿了。", exampleMeaning: "私の車はそこに停めました。" },
  { id: 2133, char: "初中", pinyin: "chūzhōng", meaning: "中学校", category: "名詞", example: "我的儿子今年就要上初中了。", exampleMeaning: "私の息子は今年もうすぐ中学校に通います。" },
  { id: 2134, char: "大学", pinyin: "dàxué", meaning: "大学", category: "名詞", example: "他刚大学毕业，在找工作。", exampleMeaning: "彼は大学を卒業したばかりで、仕事を探しています。" },
  { id: 2135, char: "电影院", pinyin: "diànyǐngyuàn", meaning: "映画館", category: "名詞", example: "我家附近有一家电影院。", exampleMeaning: "うちの近くに映画館が一つあります。" },
  { id: 2136, char: "饭馆儿", pinyin: "fànguǎnr", meaning: "レストラン", category: "名詞", example: "妈妈说今天晚上去饭馆儿吃饭。", exampleMeaning: "母は今夜、料理店に行ってご飯を食べると言いました。" },
  { id: 2137, char: "高中", pinyin: "gāozhōng", meaning: "高校", category: "名詞", example: "他们都是我高中时候的朋友。", exampleMeaning: "彼らはみんな私の高校時代の友達です。" },
  { id: 2138, char: "汉语书", pinyin: "Hànyǔ shū", meaning: "中国語の本", category: "名詞", example: "我们的汉语书很有意思。", exampleMeaning: "私たちの中国語の本はとても面白いです。" },
  { id: 2139, char: "汉字", pinyin: "Hànzì", meaning: "漢字", category: "名詞", example: "今天我学会了十个汉字。", exampleMeaning: "今日私は10個の漢字を覚えました。" },
  { id: 2140, char: "后天", pinyin: "hòutiān", meaning: "あさって", category: "名詞", example: "后天就要开学了。", exampleMeaning: "あさってには学校が始まります。" },
  { id: 2141, char: "火车", pinyin: "huǒchē", meaning: "電車", category: "名詞", example: "下了火车，就能看见汽车站。", exampleMeaning: "電車を降りると、すぐにバス停が見えます。" },
  { id: 2142, char: "今年", pinyin: "jīnnián", meaning: "今年", category: "名詞", example: "王老师今年四十六岁了。", exampleMeaning: "王先生は今年で46歳になります。" },
  { id: 2143, char: "块儿", pinyin: "kuàir", meaning: "かたまり", category: "名詞", example: "我刚吃了一块儿蛋糕。", exampleMeaning: "私はケーキを1切れ食べたばかりです。" },
  { id: 2144, char: "里面", pinyin: "lǐmiàn", meaning: "中", category: "名詞", example: "房间里面有两个人在说话。", exampleMeaning: "部屋の中には話をしている人が2人います。" },
  { id: 2145, char: "妈", pinyin: "mā", meaning: "お母さん", category: "名詞", example: "我妈做菜可好吃了。", exampleMeaning: "私の母が作る料理は本当に美味しいです。" },
  { id: 2146, char: "美国人", pinyin: "Měiguórén", meaning: "アメリカ人", category: "名詞", example: "他们都是美国人。", exampleMeaning: "彼らはみんなアメリカ人です。" },
  { id: 2147, char: "明年", pinyin: "míngnián", meaning: "来年", category: "名詞", example: "今年的冬天很冷，希望明年比较暖和。", exampleMeaning: "今年の冬はとても寒いですが、来年は少し暖かくなってほしいです。" },
  { id: 2148, char: "前天", pinyin: "qiántiān", meaning: "おととい", category: "名詞", example: "前天我在书店看见他了。", exampleMeaning: "おととい私は本屋で彼を見かけました。" },
  { id: 2149, char: "热水", pinyin: "rèshuǐ", meaning: "お湯", category: "名詞", example: "多喝热水对身体好。", exampleMeaning: "お湯をたくさん飲むのは体にいいです。" },
  { id: 2150, char: "日本人", pinyin: "Rìběnrén", meaning: "日本人", category: "名詞", example: "你是日本人吗？", exampleMeaning: "あなたは日本人ですか。" },
  { id: 2151, char: "上面", pinyin: "shàngmian", meaning: "上", category: "名詞", example: "“六”的上面是一点儿。", exampleMeaning: "「六」の上は点が1つです。" },
  { id: 2152, char: "书店", pinyin: "shūdiàn", meaning: "書店", category: "名詞", example: "学校附近哪儿有书店？", exampleMeaning: "学校の近くではどこに書店がありますか？" },
  { id: 2153, char: "听力", pinyin: "tīnglì", meaning: "リスニング", category: "名詞", example: "这次考试的听力我听不太懂。", exampleMeaning: "今回のテストのリスニングがあまり聞き取れませんでした。" },
  { id: 2154, char: "下面", pinyin: "xiàmian", meaning: "下", category: "名詞", example: "那个村子在山下面。", exampleMeaning: "あの村は山の下にあります。" },
  { id: 2155, char: "小狗", pinyin: "xiǎo gǒu", meaning: "子犬", category: "名詞", example: "我要去喂小狗了。", exampleMeaning: "私は子犬に餌をやりに行かなければなりません。" },
  { id: 2156, char: "小猫", pinyin: "xiǎo māo", meaning: "子猫", category: "名詞", example: "我家有一只小猫。", exampleMeaning: "私の家には子猫が1匹います。" },
  { id: 2157, char: "小桌子", pinyin: "xiǎo zhuōzi", meaning: "小さなテーブル", category: "名詞", example: "小桌子上面有封信，你看见了吗？", exampleMeaning: "小さいテーブルの上に手紙が1通あります、見ましたか。" },
  { id: 2158, char: "小学", pinyin: "xiǎoxué", meaning: "小学校", category: "名詞", example: "我儿子明年上小学。", exampleMeaning: "私の息子は来年小学校に上がります。" },
  { id: 2159, char: "学生们", pinyin: "xuéshengmen", meaning: "学生たち", category: "名詞", example: "学生们都来了。", exampleMeaning: "学生たちはみんな来ました。" },
  { id: 2160, char: "右面", pinyin: "yòumian", meaning: "右", category: "名詞", example: "往右面看，你就能看到学校了。", exampleMeaning: "右側を見てください、学校が見えますよ。" },
  { id: 2161, char: "阅读", pinyin: "yuèdú", meaning: "読解", category: "名詞", example: "我的爱好是阅读和运动。", exampleMeaning: "私の趣味は読書とスポーツです。" },
  { id: 2162, char: "中国人", pinyin: "Zhōngguórén", meaning: "中国人", category: "名詞", example: "她是美国人，我是中国人。", exampleMeaning: "彼女はアメリカ人で、私は中国人です。" },
  { id: 2163, char: "左面", pinyin: "zuǒmiàn", meaning: "左", category: "名詞", example: "坐在你左面的人是谁？", exampleMeaning: "あなたの左側に座っている人は誰ですか？" },
  { id: 2164, char: "不见", pinyin: "bújiàn", meaning: "見当たらない", category: "動詞", example: "我的钱包不见了。", exampleMeaning: "私の財布がなくなりました。" },
  { id: 2165, char: "吃饭", pinyin: "chī fàn", meaning: "ご飯を食べる", category: "動詞", example: "明天我们请老师吃饭。", exampleMeaning: "明日私たちは先生にご飯をごちそうします。" },
  { id: 2166, char: "打来", pinyin: "dǎlai", meaning: "電話がかかってくる", category: "動詞", example: "如果是他打来的，请告诉他我不在。", exampleMeaning: "もし彼から電話が掛かってきたら、私はいないと言ってください。" },
  { id: 2167, char: "读书", pinyin: "dúshū", meaning: "読書する、勉強する", category: "動詞", example: "他读书很多。", exampleMeaning: "彼は本をよく読みます。" },
  { id: 2168, char: "回来", pinyin: "huílai", meaning: "帰ってくる", category: "動詞", example: "妈妈去买菜了，一会儿就回来。", exampleMeaning: "母は食材を買いに行きました。少ししたらもどってきます。" },
  { id: 2169, char: "回去", pinyin: "huíqu", meaning: "帰っていく", category: "動詞", example: "已经快十点了，我们回去吧。", exampleMeaning: "もうすぐ10時です、私たち帰りましょう。" },
  { id: 2170, char: "见", pinyin: "jiàn", meaning: "会う", category: "動詞", example: "我们有十多年没见了。", exampleMeaning: "私たちは十数年会っていません。" },
  { id: 2171, char: "叫", pinyin: "jiào", meaning: "〜させる", category: "動詞", example: "老师叫他去看看。", exampleMeaning: "先生が彼にちょっと見てくるように言いました。" },
  { id: 2172, char: "开车", pinyin: "kāichē", meaning: "車を運転する", category: "動詞", example: "我正在学开车。", exampleMeaning: "私は今運転を学んでいます。" },
  { id: 2173, char: "看不见", pinyin: "kànbujiàn", meaning: "見えない", category: "動詞", example: "这儿太黑，什么也看不见。", exampleMeaning: "ここはとても暗く、何も見えません。" },
  { id: 2174, char: "没", pinyin: "méi", meaning: "〜ない（完了否定）", category: "動詞", example: "我是学生，没多少钱。", exampleMeaning: "私は学生で、お金はいくらもありません。" },
  { id: 2175, char: "睡", pinyin: "shuì", meaning: "眠る", category: "動詞", example: "他累了，回到家就睡了。", exampleMeaning: "彼は疲れていて、家に帰るとすぐに眠ってしまいました。" },
  { id: 2176, char: "说话", pinyin: "shuōhuà", meaning: "話をする", category: "動詞", example: "他一直看着我，不说话。", exampleMeaning: "彼はずっと私を見ていて、話をしませんでした。" },
  { id: 2177, char: "听不见", pinyin: "tīngbujiàn", meaning: "聞こえない", category: "動詞", example: "我什么都听不见。", exampleMeaning: "何も聞こえません。" },
  { id: 2178, char: "听见", pinyin: "tīngjiàn", meaning: "聞こえる", category: "動詞", example: "我听见有人说话，所以过来看看。", exampleMeaning: "私が人が話すのが聞こえたので、見に来ました。" },
  { id: 2179, char: "想家", pinyin: "xiǎng jiā", meaning: "ホームシックになる", category: "動詞", example: "他很想家。", exampleMeaning: "彼はとても家が恋しいです。" },
  { id: 2180, char: "写下来", pinyin: "xiěxialai", meaning: "書き留める", category: "動詞", example: "你可以把你的名字写下来吗？", exampleMeaning: "あなたの名前を書いてもらえませんか？" },
  { id: 2181, char: "学", pinyin: "xué", meaning: "学ぶ", category: "動詞", example: "现在我在中国学汉语，明年回国。", exampleMeaning: "現在私は中国で中国語を学んでいて、来年帰国します。" },
  { id: 2182, char: "住院", pinyin: "zhùyuàn", meaning: "入院する", category: "動詞", example: "我的朋友住院了，我得去看他。", exampleMeaning: "私の友だちが入院したので、私は彼を見舞いに行かなければなりません。" },
  { id: 2183, char: "做好", pinyin: "zuòhão", meaning: "ちゃんと〜する", category: "動詞", example: "你得做好准备。", exampleMeaning: "あなたはちゃんと準備をしなければなりません。" },
  { id: 2184, char: "做菜", pinyin: "zuò cài", meaning: "料理を作る", category: "動詞", example: "米饭已经做好了，马上做菜吧。", exampleMeaning: "ご飯はもうできたので、すぐに料理を作りましょう。" },
  { id: 2185, char: "做饭", pinyin: "zuò fàn", meaning: "食事を作る", category: "動詞", example: "妻子正在做饭时，丈夫回来了。", exampleMeaning: "妻がちょうど料理をしているとき、夫が帰ってきました。" },
  { id: 2186, char: "那儿", pinyin: "nàr", meaning: "そこ", category: "代名詞", example: "这儿没什么意思，我们去那儿看看吧。", exampleMeaning: "ここは面白くないから、あっちのほうをちょっと見に行きましょう。" },
  { id: 2187, char: "他们", pinyin: "tāmen", meaning: "彼ら", category: "代名詞", example: "我不认识他们。", exampleMeaning: "私は彼らと知り合いではありません。" },
  { id: 2188, char: "她们", pinyin: "tāmen", meaning: "彼女ら", category: "代名詞", example: "她们都去哪儿了？", exampleMeaning: "彼女たちはみんなどこに行きましたか。" },
  { id: 2189, char: "这么", pinyin: "zhème", meaning: "こんなに", category: "代名詞", example: "我吃不了这么多。", exampleMeaning: "私はこんなにたくさん食べきれません。" },
  { id: 2190, char: "这里", pinyin: "zhèli", meaning: "ここ", category: "代名詞", example: "这里不太亮，我们开灯吧。", exampleMeaning: "ここはあまり明るくないので、私たちは電気をつけましょう。" },
  { id: 2191, char: "这儿", pinyin: "zhèr", meaning: "ここ", category: "代名詞", example: "请在这儿写你的名字。", exampleMeaning: "ここにあなたの名前を書いてください。" },
  { id: 2192, char: "你们", pinyin: "nǐmen", meaning: "あなたたち", category: "代名詞", example: "你们现在学习忙不忙？", exampleMeaning: "あなたたちは現在勉強が忙しいですか。" },
  { id: 2193, char: "同学们", pinyin: "tóngxuémen", meaning: "同級生たち", category: "代名詞", example: "同学们都很喜欢你。", exampleMeaning: "同級生たちはみんなあなたのことが好きです。" },
  { id: 2194, char: "不太", pinyin: "bú tài", meaning: "あまり〜ない", category: "副詞", example: "我最近事情比较少，不太忙。", exampleMeaning: "私は最近用事が比較的少なく、あまり忙しくありません。" },
  { id: 2195, char: "一共", pinyin: "yígòng", meaning: "合計", category: "副詞", example: "这些东西一共多少钱？", exampleMeaning: "これらの物は全部でおいくらですか。" },
  { id: 2196, char: "不会", pinyin: "bú huì", meaning: "できない", category: "助動詞", example: "我一句汉语都不会。", exampleMeaning: "私は中国語が一言もできません。" },
  { id: 2197, char: "不少", pinyin: "bù shǎo", meaning: "少なくない、多い", category: "形容詞", example: "今天的作业真不少。", exampleMeaning: "今日の宿題は本当に多いです。" },
  { id: 2198, char: "好多", pinyin: "hǎoduō", meaning: "たくさん", category: "数量詞", example: "妈妈做了好多我爱吃的菜。", exampleMeaning: "母は私の好きな料理をとてもたくさん作りました。" },
  { id: 2199, char: "男的", pinyin: "nán de", meaning: "男性の", category: "名詞", example: "这个男的在哪里工作？", exampleMeaning: "この男性はどこで仕事をしていますか。" },
  { id: 2200, char: "女的", pinyin: "nǚ de", meaning: "女性の", category: "名詞", example: "这个女的打算几点回家？", exampleMeaning: "この女性は何時に家に帰るつもりですか？" },
  { id: 2201, char: "有点儿", pinyin: "yǒudiǎnr", meaning: "少し", category: "副詞", example: "北京的冬天有点儿冷。", exampleMeaning: "北京の冬は少し寒いです。" },
  { id: 2202, char: "一些", pinyin: "yìxiē", meaning: "少し", category: "数量詞", example: "我买了一些家里用的东西。", exampleMeaning: "私は家で使うものを少し買いました。" },
  { id: 2203, char: "点儿", pinyin: "diǎnr", meaning: "少し", category: "数量詞", example: "你想买点儿什么？", exampleMeaning: "あなたは何を買いたいですか？" },
  { id: 2204, char: "多", pinyin: "duō", meaning: "〜過ぎ、多い", category: "形容詞", example: "十二点多了，咱们吃饭吧。", exampleMeaning: "12時過ぎました。私達はご飯にしましょう。" },
  { id: 2205, char: "哪里", pinyin: "nǎli", meaning: "どこ", category: "疑問詞", example: "喂，你是哪里？", exampleMeaning: "もしもし、あなたはどこにいますか？" },
  { id: 2206, char: "次", pinyin: "cì", meaning: "回", category: "量詞", example: "我给他打过两次电话了。", exampleMeaning: "私は彼に2回電話をかけました。" },
  { id: 2207, char: "分", pinyin: "fēn", meaning: "分", category: "量詞", example: "飞机到达的时间是九点二十分。", exampleMeaning: "飛行機が到着する時間は9時20分です。" },
  { id: 2208, char: "第", pinyin: "dì", meaning: "第〜", category: "接頭語", example: "我第一次坐飞机是十二岁。", exampleMeaning: "私が初めて飛行機に乗ったのは12歳のときです。" },
  { id: 2209, char: "好的", pinyin: "hǎo de", meaning: "いいよ", category: "フレーズ", example: "明天见，好吗？—好的，明天见。", exampleMeaning: "明日会いましょう、いいですか。—はい、明日会いましょう。" },
  { id: 2210, char: "几个", pinyin: "jǐ ge", meaning: "いくつか", category: "数量詞", example: "我买了几个苹果，你们吃吧。", exampleMeaning: "リンゴをいくつか買ったので、あなたたち食べてください。" },
  { id: 2211, char: "几天", pinyin: "jǐ tiān", meaning: "何日間", category: "数量詞", example: "你一个星期工作几天？", exampleMeaning: "あなたは一週間に何日仕事をしていますか。" },
  { id: 2212, char: "例如", pinyin: "lìrú", meaning: "例えば", category: "接続詞", example: "我有很多想去的地方，例如北京。", exampleMeaning: "私は行きたい場所がたくさんあります。例えば北京がそうです。" },
  { id: 2213, char: "哪年", pinyin: "nǎ nián", meaning: "何年", category: "疑問詞", example: "你是哪一年大学毕业的？", exampleMeaning: "あなたは何年に大学を卒業しますか。" },
  { id: 2214, char: "哪天", pinyin: "nǎ tiān", meaning: "いつ", category: "疑問詞", example: "哪天咱们一起去公园玩儿。", exampleMeaning: "いつか私達で一緒に公園へ遊びに行きましょう。" },
  { id: 2215, char: "你看", pinyin: "nǐ kàn", meaning: "見て", category: "フレーズ", example: "你看，前面就是银行。", exampleMeaning: "見てください、前に銀行があります。" },
  { id: 2216, char: "上小学", pinyin: "shàng xiǎoxué", meaning: "小学校に通う", category: "動詞", example: "他的儿子正在上小学。", exampleMeaning: "彼の息子は今小学校に通っています。" },
  { id: 2217, char: "是", pinyin: "shì", meaning: "はい", category: "フレーズ", example: "请问，你是大卫吗？—是，我是。", exampleMeaning: "すみません、あなたはデビッドさんですか。—はい、そうです。" },
  { id: 2218, char: "是的", pinyin: "shì de", meaning: "そうです", category: "フレーズ", example: "你是美国人吗？—是的，我是。", exampleMeaning: "あなたはアメリカ人ですか。—はい、そうです。" },
  { id: 2219, char: "是吗", pinyin: "shì ma", meaning: "そうですか", category: "フレーズ", example: "我很喜欢看电影。—是吗？", exampleMeaning: "私は映画を見るのがとても好きです。—そうですか。" },
  { id: 2220, char: "是...的", pinyin: "shì...de", meaning: "〜のだ", category: "構文", example: "这张桌子是他自己做的。", exampleMeaning: "このテーブルは彼自身が作ったものです。" },
  { id: 2221, char: "太...了", pinyin: "tài...le", meaning: "〜すぎる", category: "構文", example: "这本词典太大了。", exampleMeaning: "この辞書は大きすぎます。" },
  { id: 2222, char: "我回来了", pinyin: "wǒ huílai le", meaning: "ただいま", category: "フレーズ", example: "妈妈，我回来了。", exampleMeaning: "お母さん、ただいま。" },
  { id: 2223, char: "有人", pinyin: "yǒu rén", meaning: "誰か", category: "フレーズ", example: "有人来了，去开门。", exampleMeaning: "誰かが来たので、ドアを開けに行きます。" },

  // ■ HSK 2級 生活語句 (抜粋)
  { id: 2224, char: "星期天", pinyin: "xīngqītiān", meaning: "日曜日", category: "カレンダー", example: "星期天我休息。", exampleMeaning: "日曜日は休みです。" },
  { id: 2225, char: "星期一", pinyin: "xīngqīyī", meaning: "月曜日", category: "カレンダー", example: "今天是星期一。", exampleMeaning: "今日は月曜日です。" },
  { id: 2226, char: "一月", pinyin: "yīyuè", meaning: "1月", category: "カレンダー", example: "一月是一年的开始。", exampleMeaning: "1月は一年の始まりです。" },
  { id: 2227, char: "拜拜", pinyin: "bàibai", meaning: "バイバイ", category: "定型表現", example: "拜拜，明天见。", exampleMeaning: "バイバイ、また明日。" },
  { id: 2228, char: "帮忙", pinyin: "bāngmáng", meaning: "手伝う", category: "動詞", example: "你能帮个忙吗？", exampleMeaning: "ちょっと手伝ってくれませんか。" },
  { id: 2229, char: "抱歉", pinyin: "bàoqiàn", meaning: "ごめんなさい", category: "定型表現", example: "抱歉，我来晚了。", exampleMeaning: "ごめんなさい、遅くなりました。" },
  { id: 2230, char: "别害羞", pinyin: "bié hàixiū", meaning: "恥ずかしがらないで", category: "定型表現", example: "别害羞，大家都是朋友。", exampleMeaning: "恥ずかしがらないで、みんな友達だよ。" },
  { id: 2231, char: "别见外", pinyin: "bié jiànwài", meaning: "遠慮しないで", category: "定型表現", example: "别见外，多吃点。", exampleMeaning: "遠慮しないで、たくさん食べて。" },
  { id: 2232, char: "别紧张", pinyin: "bié jǐnzhāng", meaning: "緊張しないで", category: "定型表現", example: "别紧张，慢慢说。", exampleMeaning: "緊張しないで、ゆっくり話して。" },
  { id: 2233, char: "别忘了", pinyin: "bié wàng le", meaning: "忘れないで", category: "定型表現", example: "别忘了明天的考试。", exampleMeaning: "明日の試験を忘れないで。" },
  { id: 2234, char: "别着急", pinyin: "bié zháojí", meaning: "焦らないで", category: "定型表現", example: "别着急，还有时间。", exampleMeaning: "焦らないで、まだ時間はあるから。" },
  { id: 2235, char: "别管我", pinyin: "bié guǎn wǒ", meaning: "放っておいて", category: "定型表現", example: "别管我，我想一个人静静。", exampleMeaning: "放っておいて、一人で静かにしたいんだ。" },
  { id: 2236, char: "比如", pinyin: "bǐrú", meaning: "例えば", category: "接続詞", example: "我喜欢水果，比如苹果、香蕉。", exampleMeaning: "私は果物が好きです、例えばリンゴやバナナなど。" },
  { id: 2237, char: "不敢当", pinyin: "bù gǎndāng", meaning: "とんでもない", category: "定型表現", example: "您过奖了，不敢当。", exampleMeaning: "褒めすぎです、とんでもないです。" },
  { id: 2238, char: "不可能", pinyin: "bù kěnéng", meaning: "ありえない", category: "フレーズ", example: "这绝对不可能。", exampleMeaning: "それは絶対にありえません。" },
  { id: 2239, char: "不谢", pinyin: "bú xiè", meaning: "どういたしまして", category: "定型表現", example: "谢谢你！—不谢。", exampleMeaning: "ありがとう！—どういたしまして。" },
  { id: 2240, char: "不知道", pinyin: "bù zhīdào", meaning: "わかりません", category: "フレーズ", example: "我不知道他在哪儿。", exampleMeaning: "彼がどこにいるか分かりません。" },
  { id: 2241, char: "不错", pinyin: "búcuò", meaning: "なかなか良い", category: "形容詞", example: "这件衣服不错。", exampleMeaning: "この服はなかなか良いです。" },
  { id: 2242, char: "不要紧", pinyin: "búyàojǐn", meaning: "差し支えない", category: "定型表現", example: "没关系，不要紧。", exampleMeaning: "大丈夫、差し支えありません。" },
  { id: 2243, char: "差不多", pinyin: "chàbuduō", meaning: "ほぼ", category: "形容詞", example: "我们俩差不多高。", exampleMeaning: "私たち二人はほぼ同じ背の高さです。" },
  { id: 2244, char: "吃好了", pinyin: "chī hǎo le", meaning: "食べ終わる", category: "フレーズ", example: "我吃好了，大家慢用。", exampleMeaning: "ごちそうさまでした、皆さんごゆっくり。" },
  { id: 2245, char: "吃什么？", pinyin: "chī shénme?", meaning: "何食べる？", category: "フレーズ", example: "今晚吃什么？", exampleMeaning: "今夜は何を食べる？" },
  { id: 2246, char: "初次见面", pinyin: "chūcì jiànmiàn", meaning: "初めまして", category: "定型表現", example: "初次见面，请多关照。", exampleMeaning: "初めまして、よろしくお願いします。" },
  { id: 2247, char: "吹了", pinyin: "chuī le", meaning: "だめになった", category: "フレーズ", example: "那件事吹了。", exampleMeaning: "あの件はだめになりました。" },
  { id: 2248, char: "大概", pinyin: "dàgài", meaning: "だいたい", category: "副詞", example: "他大概十点到。", exampleMeaning: "彼はだいたい10時に着きます。" },
  { id: 2249, char: "大家好", pinyin: "dàjiā hǎo", meaning: "みなさんこんにちは", category: "定型表現", example: "大家好，我是新来的。", exampleMeaning: "みなさんこんにちは、私は新入りです。" },
  { id: 2250, char: "当然了", pinyin: "dāngrán le", meaning: "もちろんです", category: "定型表現", example: "你可以帮我吗？—当然了。", exampleMeaning: "手伝ってくれますか？—もちろんです。" },
  { id: 2251, char: "当真", pinyin: "dàngzhēn", meaning: "本気にする", category: "動詞", example: "我是开玩笑的，别当真。", exampleMeaning: "冗談だよ、本気にしないで。" },
  { id: 2252, char: "对", pinyin: "duì", meaning: "その通り", category: "フレーズ", example: "你是李明吗？—对。", exampleMeaning: "あなたは李明ですか？—その通りです。" },
  { id: 2253, char: "赶上了", pinyin: "gǎn shàng le", meaning: "間に合った", category: "フレーズ", example: "还好赶上了火车。", exampleMeaning: "なんとか電車に間に合いました。" },
  { id: 2254, char: "干杯", pinyin: "gānbēi", meaning: "乾杯", category: "定型表現", example: "为我们的友谊干杯！", exampleMeaning: "私たちの友情に乾杯！" },
  { id: 2255, char: "给你", pinyin: "gěi nǐ", meaning: "はい、どうぞ", category: "フレーズ", example: "给你，这是你要的书。", exampleMeaning: "はいどうぞ、これがあなたの欲しかった本です。" },
  { id: 2256, char: "恭喜你", pinyin: "gōngxǐ nǐ", meaning: "おめでとう", category: "定型表現", example: "恭喜你考上了大学！", exampleMeaning: "大学合格おめでとう！" },
  { id: 2257, char: "还行", pinyin: "hái xíng", meaning: "まあまあ", category: "フレーズ", example: "身体怎么样？—还行。", exampleMeaning: "体調はどう？—まあまあだよ。" },
  { id: 2258, char: "韩元", pinyin: "hányuán", meaning: "韓国ウォン", category: "名詞", example: "一万韩元。", exampleMeaning: "1万ウォン。" },
  { id: 2259, char: "好", pinyin: "hǎo", meaning: "よい", category: "形容詞", example: "天气很好。", exampleMeaning: "天気がとても良い。" },
  { id: 2260, char: "好吧", pinyin: "hǎo ba", meaning: "わかりました", category: "フレーズ", example: "好吧，我同意。", exampleMeaning: "わかりました、同意します。" },
  { id: 2261, char: "好主意", pinyin: "hǎo zhǔyi", meaning: "いいアイデアですね", category: "フレーズ", example: "去爬山？好主意！", exampleMeaning: "山登り？いいアイデアだね！" },
  { id: 2262, char: "好久不见了", pinyin: "hǎojiǔ bújiàn le", meaning: "お久しぶりです", category: "定型表現", example: "好久不见了，你还好吗？", exampleMeaning: "お久しぶりです、お元気ですか？" },
  { id: 2263, char: "很酷", pinyin: "hěn kù", meaning: "かっこいい", category: "形容詞", example: "他戴着墨镜，很酷。", exampleMeaning: "彼はサングラスをかけていて、とてもかっこいい。" },
  { id: 2264, char: "欢迎", pinyin: "huānyíng", meaning: "ようこそ", category: "定型表現", example: "欢迎光临。", exampleMeaning: "いらっしゃいませ。" },
  { id: 2265, char: "灰心", pinyin: "huīxīn", meaning: "がっかりする", category: "動詞", example: "别灰心，下次再努力。", exampleMeaning: "がっかりしないで、次は頑張ろう。" },
  { id: 2266, char: "几点了？", pinyin: "jǐ diǎn le?", meaning: "何時ですか？", category: "フレーズ", example: "请问，几点了？", exampleMeaning: "すみません、何時ですか？" },
  { id: 2267, char: "加油", pinyin: "jiāyóu", meaning: "頑張れ", category: "定型表現", example: "加油！你能行！", exampleMeaning: "頑張れ！君ならできる！" },
  { id: 2268, char: "继续说", pinyin: "jìxù shuō", meaning: "しゃべり続ける", category: "フレーズ", example: "请继续说下去。", exampleMeaning: "話を続けてください。" },
  { id: 2269, char: "看情况", pinyin: "kàn qíngkuàng", meaning: "状況を見る", category: "フレーズ", example: "去不去要看情况。", exampleMeaning: "行くかどうかは状況次第です。" },
  { id: 2270, char: "可惜", pinyin: "kěxī", meaning: "惜しい、残念", category: "形容詞", example: "真可惜，没赶上火车。", exampleMeaning: "本当に残念、電車に間に合わなかった。" },
  { id: 2271, char: "可以", pinyin: "kěyǐ", meaning: "できる、よい", category: "助動詞", example: "我可以进来吗？", exampleMeaning: "入ってもいいですか？" },
  { id: 2272, char: "快点儿", pinyin: "kuài diǎnr", meaning: "早くして", category: "フレーズ", example: "快点儿，要迟到了。", exampleMeaning: "早くして、遅刻しちゃうよ。" },
  { id: 2273, char: "里面请", pinyin: "lǐmiàn qǐng", meaning: "中へどうぞ", category: "定型表現", example: "客人来了，里面请。", exampleMeaning: "お客様が来ました、中へどうぞ。" },
  { id: 2274, char: "麻烦你了", pinyin: "máfan nǐ le", meaning: "お手数おかけします", category: "定型表現", example: "这事就麻烦你了。", exampleMeaning: "この件はお手数おかけします。" },
  { id: 2275, char: "买单", pinyin: "mǎidān", meaning: "お会計", category: "動詞", example: "服务员，买单。", exampleMeaning: "店員さん、お会計お願いします。" },
  { id: 2276, char: "没错吗", pinyin: "méi cuò ma", meaning: "間違いないですか", category: "フレーズ", example: "你确定没错吗？", exampleMeaning: "本当に間違いないですか？" },
  { id: 2277, char: "没问题", pinyin: "méi wèntí", meaning: "問題ない", category: "フレーズ", example: "包在我身上，没问题。", exampleMeaning: "私に任せて、問題ないよ。" },
  { id: 2278, char: "明天见", pinyin: "míngtiān jiàn", meaning: "また明日", category: "定型表現", example: "下班了，明天见。", exampleMeaning: "仕事終わり、また明日。" },
  { id: 2279, char: "你多大了？", pinyin: "nǐ duō dà le?", meaning: "あなたはおいくつですか？", category: "フレーズ", example: "小朋友，你多大了？", exampleMeaning: "お嬢ちゃん、いくつになったの？" },
  { id: 2280, char: "你好", pinyin: "nǐ hǎo", meaning: "こんにちは", category: "定型表現", example: "老师，你好。", exampleMeaning: "先生、こんにちは。" },
  { id: 2281, char: "你几岁了", pinyin: "nǐ jǐ suì le", meaning: "あなたは何歳ですか", category: "フレーズ", example: "你几岁了？", exampleMeaning: "何歳ですか？（子供に対して）" },
  { id: 2282, char: "你叫什么名字", pinyin: "nǐ jiào shénme míngzi", meaning: "お名前は何ですか", category: "フレーズ", example: "请问，你叫什么名字？", exampleMeaning: "すみません、お名前は何ですか？" },
  { id: 2283, char: "你呢？", pinyin: "nǐ ne?", meaning: "あなたは？", category: "フレーズ", example: "我是中国人，你呢？", exampleMeaning: "私は中国人です、あなたは？" },
  { id: 2284, char: "你说呢？", pinyin: "nǐ shuō ne?", meaning: "どう思う？", category: "フレーズ", example: "这事怎么办，你说呢？", exampleMeaning: "これはどうしようか、君はどう思う？" },
  { id: 2285, char: "您贵姓？", pinyin: "nín guìxìng?", meaning: "お名前は？", category: "フレーズ", example: "先生，您贵姓？", exampleMeaning: "お客様、お名前は？（敬語）" },
  { id: 2286, char: "您好", pinyin: "nín hǎo", meaning: "こんにちは（敬語）", category: "定型表現", example: "爷爷，您好。", exampleMeaning: "おじいさん、こんにちは。" },
  { id: 2287, char: "您慢走", pinyin: "nín màn zǒu", meaning: "どうぞお気をつけて", category: "定型表現", example: "再见，您慢走。", exampleMeaning: "さようなら、どうぞお気をつけて。" },
  { id: 2288, char: "您请", pinyin: "nín qǐng", meaning: "あなたにお願いします", category: "フレーズ", example: "这事还得您请。", exampleMeaning: "この件はやはりあなたにお願いします。" },
  { id: 2289, char: "您先请", pinyin: "nín xiān qǐng", meaning: "お先にどうぞ", category: "定型表現", example: "电梯来了，您先请。", exampleMeaning: "エレベーターが来ました、お先にどうぞ。" },
  { id: 2290, char: "茄子！", pinyin: "qiézi!", meaning: "チーズ！", category: "定型表現", example: "拍照了，大家喊“茄子”！", exampleMeaning: "写真撮るよ、みんな「チーズ」って言って！" },
  { id: 2291, char: "请等一下", pinyin: "qǐng děng yíxià", meaning: "少々お待ちください", category: "定型表現", example: "请等一下，我马上回来。", exampleMeaning: "少々お待ちください、すぐ戻ります。" },
  { id: 2292, char: "请多关照", pinyin: "qǐng duō guānzhào", meaning: "よろしくお願いします", category: "定型表現", example: "以后请多关照。", exampleMeaning: "これからよろしくお願いします。" },
  { id: 2293, char: "请进", pinyin: "qǐng jìn", meaning: "お入りください", category: "定型表現", example: "敲门后，老师说“请进”。", exampleMeaning: "ノックした後、先生は「お入りください」と言った。" },
  { id: 2294, char: "请留步", pinyin: "qǐng liúbù", meaning: "ここで結構です", category: "定型表現", example: "不用送了，请留步。", exampleMeaning: "送らなくて大丈夫です、ここで結構です。" },
  { id: 2295, char: "请再说一遍", pinyin: "qǐng zài shuō yí biàn", meaning: "もう一度言ってください", category: "フレーズ", example: "我没听清，请再说一遍。", exampleMeaning: "よく聞こえませんでした、もう一度言ってください。" },
  { id: 2296, char: "请坐", pinyin: "qǐng zuò", meaning: "座ってください", category: "定型表現", example: "别客气，请坐。", exampleMeaning: "遠慮しないで、座ってください。" },
  { id: 2297, char: "请问", pinyin: "qǐngwèn", meaning: "おたずねしますが", category: "定型表現", example: "请问，车站在哪儿？", exampleMeaning: "おたずねしますが、駅はどこですか？" },
  { id: 2298, char: "求求你", pinyin: "qiúqiú nǐ", meaning: "お願い", category: "フレーズ", example: "求求你，帮帮我吧。", exampleMeaning: "お願い、助けて。" },
  { id: 2299, char: "让你久等了", pinyin: "ràng nǐ jiǔ děng le", meaning: "お待たせしました", category: "定型表現", example: "不好意思，让你久等了。", exampleMeaning: "すみません、お待たせしました。" },
  { id: 2300, char: "人民币", pinyin: "rénmínbì", meaning: "人民元", category: "名詞", example: "一百块人民币。", exampleMeaning: "100人民元。" },
  { id: 2301, char: "日元", pinyin: "rìyuán", meaning: "日本円", category: "名詞", example: "一千日元。", exampleMeaning: "1000円。" },
  { id: 2302, char: "生日快乐！", pinyin: "shēngrì kuàilè!", meaning: "お誕生日おめでとう！", category: "定型表現", example: "祝你生日快乐！", exampleMeaning: "お誕生日おめでとう！" },
  { id: 2303, char: "什么时候？", pinyin: "shénme shíhou?", meaning: "いつですか？", category: "フレーズ", example: "你什么时候回来？", exampleMeaning: "いつ帰ってくるの？" },
  { id: 2304, char: "说好了", pinyin: "shuō hǎo le", meaning: "約束しました", category: "フレーズ", example: "我们说好了明天去。", exampleMeaning: "明日行くって約束したよね。" },
  { id: 2305, char: "随便用", pinyin: "suíbiàn yòng", meaning: "ご自由にお使いください", category: "フレーズ", example: "这笔你随便用。", exampleMeaning: "このペンはご自由にお使いください。" },
  { id: 2306, char: "太好了", pinyin: "tài hǎo le", meaning: "いいね", category: "フレーズ", example: "明天放假，太好了！", exampleMeaning: "明日は休みだ、やったね！" },
  { id: 2307, char: "讨厌", pinyin: "tǎoyàn", meaning: "嫌い", category: "形容詞", example: "我讨厌下雨天。", exampleMeaning: "雨の日は嫌いです。" },
  { id: 2308, char: "听你的", pinyin: "tīng nǐ de", meaning: "あなたの言う通りにします", category: "フレーズ", example: "好吧，听你的。", exampleMeaning: "わかった、君の言う通りにするよ。" },
  { id: 2309, char: "同意", pinyin: "tóngyì", meaning: "同意する", category: "動詞", example: "我完全同意你的看法。", exampleMeaning: "あなたの意見に完全に同意します。" },
  { id: 2310, char: "我看", pinyin: "wǒ kàn", meaning: "私の考えでは", category: "フレーズ", example: "我看这事不简单。", exampleMeaning: "私の考えでは、これは簡単ではない。" },
  { id: 2311, char: "我来", pinyin: "wǒ lái", meaning: "私がやります", category: "フレーズ", example: "放着别动，我来。", exampleMeaning: "そのままにして、私がやります。" },
  { id: 2312, char: "我请客", pinyin: "wǒ qǐngkè", meaning: "私がおごります", category: "フレーズ", example: "今天我请客，大家随便吃。", exampleMeaning: "今日は私がおごるから、みんな好きに食べて。" },
  { id: 2313, char: "我先走了", pinyin: "wǒ xiān zǒu le", meaning: "お先に失礼します", category: "定型表現", example: "各位，我先走了。", exampleMeaning: "皆さん、お先に失礼します。" },
  { id: 2314, char: "无所谓", pinyin: "wúsuǒwèi", meaning: "どうでもいい", category: "フレーズ", example: "吃什么都行，我无所谓。", exampleMeaning: "何を食べてもいいよ、僕はどうでもいい。" },
  { id: 2315, char: "小意思", pinyin: "xiǎo yìsi", meaning: "心ばかりのもの", category: "フレーズ", example: "这点礼物，小意思。", exampleMeaning: "これっぽっちのプレゼントですが、ほんの気持ちです。" },
  { id: 2316, char: "辛苦了", pinyin: "xīnkǔ le", meaning: "ご苦労様です", category: "定型表現", example: "大家辛苦了。", exampleMeaning: "みなさんお疲れ様でした。" },
  { id: 2317, char: "新年快乐！", pinyin: "xīnnián kuàilè!", meaning: "あけましておめでとう！", category: "定型表現", example: "新年快乐，万事如意！", exampleMeaning: "あけましておめでとう、全て順調でありますように！" },
  { id: 2318, char: "一路平安", pinyin: "yílù píng'ān", meaning: "道中ご無事で", category: "定型表現", example: "祝你一路平安！", exampleMeaning: "道中ご無事で！" },
  { id: 2319, char: "有道理", pinyin: "yǒu dàolǐ", meaning: "理にかなっている", category: "フレーズ", example: "你说得有道理。", exampleMeaning: "君の言うことはもっともだ。" },
  { id: 2320, char: "元（块）", pinyin: "yuán", meaning: "元", category: "名詞", example: "五元钱。", exampleMeaning: "5元。" },
  { id: 2321, char: "再说吧", pinyin: "zài shuō ba", meaning: "またあとにしましょう", category: "フレーズ", example: "这事以后再说吧。", exampleMeaning: "この件はまた後で話しましょう。" },
  { id: 2322, char: "赞成", pinyin: "zànchéng", meaning: "賛成する", category: "動詞", example: "大家都很赞成这个计划。", exampleMeaning: "みんなその計画に賛成しています。" },
  { id: 2323, char: "糟了", pinyin: "zāo le", meaning: "まずい", category: "フレーズ", example: "糟了，我忘了带钥匙。", exampleMeaning: "しまった、鍵を忘れた。" },
  { id: 2324, char: "怎么办？", pinyin: "zěnme bàn?", meaning: "どうしましょう", category: "フレーズ", example: "车坏了，怎么办？", exampleMeaning: "車が壊れた、どうしよう？" },
  { id: 2325, char: "怎么了？", pinyin: "zěnme le?", meaning: "どうしました？", category: "フレーズ", example: "你脸色不好，怎么了？", exampleMeaning: "顔色が悪いけど、どうしたの？" },
  { id: 2326, char: "真棒", pinyin: "zhēn bàng", meaning: "すばらしい", category: "形容詞", example: "你的表现真棒！", exampleMeaning: "君のパフォーマンスは素晴らしい！" },
  { id: 2327, char: "真的", pinyin: "zhēn de", meaning: "ほんとうに", category: "副詞", example: "我真的很高兴。", exampleMeaning: "私は本当に嬉しいです。" },
  { id: 2328, char: "真烦人", pinyin: "zhēn fán rén", meaning: "やっかいだ", category: "フレーズ", example: "这蚊子真烦人。", exampleMeaning: "この蚊は本当にうっとうしい。" },
  { id: 2329, char: "真精神", pinyin: "zhēn jīngshén", meaning: "元気である", category: "フレーズ", example: "爷爷看起来真精神。", exampleMeaning: "おじいさんはとても元気そうだ。" },
  { id: 2330, char: "真帅", pinyin: "zhēn shuài", meaning: "かっこいい", category: "形容詞", example: "他今天穿得真帅。", exampleMeaning: "彼は今日とてもかっこいい服を着ている。" },
  { id: 2331, char: "正合适", pinyin: "zhèng héshì", meaning: "おあつらえ向き", category: "フレーズ", example: "这双鞋大小正合适。", exampleMeaning: "この靴のサイズはぴったりだ。" },
  { id: 2332, char: "知道了", pinyin: "zhīdao le", meaning: "わかりました", category: "フレーズ", example: "好的，我知道了。", exampleMeaning: "はい、わかりました。" }
];